models:
  evaluator: "unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q5_K_S"
  optimizer: "unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q5_K_S"
  embed: "Qwen/Qwen3-Embedding-4B-GGUF:F16"

llama_cpp:
  host: "http://127.0.0.1:8080"
  llm_api_url: "http://127.0.0.1:8080"
  embed_api_url: "http://127.0.0.1:8081"

comfyui:
  api_url: "http://127.0.0.1:8188"
  workflow_file: "krea-2-basic.json"
  models_dir: "./ComfyUI/models"
  custom_nodes_dir: "" # "./ComfyUI/custom_nodes"

containers:
  comfyui:
    image: "evo-prompt/comfy-api-server"
    name: "comfyui-server"
    build: "comfyui"
    port: 8188
    health_url: "http://127.0.0.1:8188/system_stats"
    health_timeout: 180
  llama_cpp:
    image: "ghcr.io/ggml-org/llama.cpp:full-cuda12-b10200"
    name: "llama-cpp-server"
    port: 8080
    health_url: "http://127.0.0.1:8080/health"
    health_timeout: 3600
  embed:
    image: "ghcr.io/ggml-org/llama.cpp:full-cuda12-b10200"
    name: "embed-server"
    port: 8081
    health_url: "http://127.0.0.1:8081/health"
    health_timeout: 3600
